# Generated by Django 4.2 on 2023-05-17 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(default='default_username', max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(choices=[(1, 'Room1'), (2, 'Room2'), (3, 'Room3'), (4, 'Room4'), (5, 'Room5'), (6, 'Room6'), (7, 'Room7'), (8, 'Room8'), (9, 'Room9'), (10, 'Room10'), (11, 'Room11'), (12, 'Room12'), (13, 'Room13'), (14, 'Room14'), (15, 'Room15'), (16, 'Room16'), (17, 'Room17'), (18, 'Room18'), (19, 'Room19'), (20, 'Room20'), (21, 'Room21'), (22, 'Room22'), (23, 'Room23'), (24, 'Room24'), (25, 'Room25'), (26, 'Room26'), (27, 'Room27'), (28, 'Room28'), (29, 'Room29'), (30, 'Room30'), (31, 'Room31'), (32, 'Room32'), (33, 'Room33'), (34, 'Room34'), (35, 'Room35'), (36, 'Room36'), (37, 'Room37'), (38, 'Room38'), (39, 'Room39'), (40, 'Room40'), (41, 'Room41'), (42, 'Room42'), (43, 'Room43'), (44, 'Room44'), (45, 'Room45'), (46, 'Room46'), (47, 'Room47'), (48, 'Room48'), (49, 'Room49'), (50, 'Room50'), (51, 'Room51')], unique=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pickup_time', models.CharField(default='None', max_length=20)),
                ('dropoff_time', models.CharField(blank=True, default='nothing', max_length=20, null=True)),
                ('guest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='regora_app.room')),
                ('services', models.ManyToManyField(to='regora_app.service')),
            ],
        ),
    ]
